# Generated by Django 3.2.12 on 2022-02-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTags',
            new_name='Tags',
        ),
    ]
