# Generated by Django 4.0.2 on 2022-02-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog', '0002_account_alter_comment_user_id_alter_post_user_id_and_more'),
        ('dj_blog', '0002_rename_posttags_tags'),
    ]

    operations = [
    ]
