# Generated by Django 3.2.12 on 2022-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog', '0002_auto_20220210_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=50),
        ),
    ]
